class StringNames{
           public static void main(String[] args){
                 String fname="java";
                 String lname=new String("lab");
                 String labname=fname+lname;
                 String cls="AI&DS";
                 String  sec="A";
                 String class_name=cls.concat(sec);       System.out.println("WELCOME TO "+labname+""+class_name);
    }
}                                                                                                                                                                                                                                                                                                    